### ISSUE TITLE
`cry d generator name` not working

### ISSUE THREAD

**Issue by clozach** [pedsmoreira/battlecry#9]
Unless I'm misunderstanding the docs, the `d` command isn't working, at least not in the context of the default generator. (If it _is_ working and I've just misunderstood how to use battlecry, maybe this could be considered a _documentation_ bug instead.)

**Steps to reproduce:**

```
bash-3.2$ cry g init

🥁  Playing: generate init

   🥁  Playing: generate generator
      ✅  File created: battlecry/generators/component/component.generator.js
      ✅  File created: battlecry/generators/component/templates/__na-me__.txt

   ✅  File created: battlecry/battlecry-setup.js

   🥁  Playing: generate component
      ✅  File created: it-worked/components/test-abc.txt

bash-3.2$ cry g component HelloWorld

🥁  Playing: generate component
   ✅  File created: it-worked/components/hello-world.txt

bash-3.2$ cry d component HelloWorld
Usage: cry <method> <generator> [args] [options]

Options:

  -V, --version  output the version number
  -A, --about    output info about Battlecry contributors
  -h, --help     output usage information

Commands:

  
🥁  generator

   cry g generator name
   Generate a new generator

   cry download generator repository
   Download one or more generators from GitHub
       -d --dir value 	The repository directory where the generators are located

   cry d generator name
   Destroy an existing generator

🥁  init

   cry g init 

🥁  component

   cry g component name
       -s --special 	Special option

⚠️  Command not found. Check the commands available above

bash-3.2$ 
```

**Comment by pedsmoreira** [comment]
Hi @clozach, thanks for opening this issue.

In fact, the `destroy` (`d`) method isn't generated by default.

If you wish to delete the `HelloWorld` generator, the command would be `cry d generator HelloWorld`. If you think the docs can be improved to clarify this I'd love to hear your ideas.

What comes to my mind is an explanation of what each piece of the command means, such as:
`cry g component test`
- cry: the battlecry command
- g (alias to generate): the method
- component: the generator
- test: an arg provided to the method

Let me know if you have any other questions.
Cheers!

**Comment by clozach** [comment]
Hey, @pedsmoreira. Sure thing!

I think my thoughts about this thing you've created are still a bit too tangled for me to make specific recommendations. Instead, here are some questions whose responses would probably help others as well:

- What is the difference between `cry g init` and `cry g generator your_generator_name_here`? When would I use one or the other? How do both relate to `cry download …`?

- How do I use _battlecry/battlecry-setup.js_? Can you show examples of 1 or 2 primary use cases?

- Can you walk me through a practical scenario for Battlecry, start to finish?

Oh, and one last thing I find _really_ helpful when it's covered in a project's README: What similar tools do you know about, either in js or other languages, and what are some key differences and similarities between them and Battlecry?

Looking forward to giving it another try!
Cheers 🙂

**Comment by pedsmoreira** [comment]
These are very good questions @clozach, thanks! Since I'm the one who created the library the docs seem very clear to me, so questions like yours are very helpful when it comes on understanding how to better explain the concepts behind Battlecry.

## First Question: `cry g init` vs `cry g generator name` vs `cry download generator`

### Cry g init
`cry g init` generates a `battlecry-setup.js` file for you to configure your project, calls `cry g generator component` and immediately runs this generator as `cry g component test-abc`. The goal of `init` is to give an initial view of what battlecry looks like, my idea was that it would be used only once, when you start the project.

### Cry g generator
`cry g generator` creates a generator for you given a name, I'll give you an example. Let's say you just started your application and you have 3 parts: controllers, models and views. Battlecry can help you creating scaffolds for you, so that you don't have to copy and paste files every time you wish to create a new controller, model or view. So you'll create one generator for each one:
```sh
cry g generator controller
cry g generator model
cry g generator view
```

These commands will basically create empty `.generator.js` files with some empty templates for you to edit. - Fun fact: if you look into battlecry's source code you'll see that there is a `generator.generator.js` with a `generate` method in it, which is the command you just called three times.

Now, it's not uncommon for you to want to generate a controllers, model and views, all at once, for a specific resource. Let's say you wish to create a `User.js` model, a `ListUsers.js` view, a `ShowUser.js` view and a `UserController.js`, you could have a generator call these other generators you just created:

```
cry g generator scaffold // create a new generator
// implement your generator, calling the generators you created before
cry g scaffold user
```


https://github.com/pedsmoreira/battlecry#customizing-your-battlecry-setupjs

**Comment by clozach** [comment]
Hi Pedro,

I finally got around to looking at Battlecry again, and once again found myself unnecessarily confused. 

This time, I persevered, browsing your code, docs, and the above response until I truly understood the basics. Then I wrote [this fictional tutorial](https://gist.github.com/clozach/8eb4472017cdd992fe7b617308965ef0). I say, "fictional" because I'm sure I've made some factual errors, I've left out an entire section, and because I've posited a built-in `scaffold` generator to replace `generator`.

Take a look! If you like what you see, let me know. I haven't got a strong use case for `cry` yet, but it _seems_ worth learning, and I learn best when I'm trying to explain something…all of which is to say, I'm happy to help with the docs if you're interested.

**Comment by pedsmoreira** [comment]
Hi @clozach,

I really like what you did there with the tutorial. I'm not a big fan of `cry generate generator` neither, the words are too similar and it gets confusing, I just hadn't thought of a better name. I like the idea of renaming it to `scaffold` and getting rid of `init`.

I can see this format of having multiple tutorials much easier to understand, with different layers of details (basic tutorial for beginners and more advanced ones for those who need customisation). 

This week I probably won't have much time to go further on the documentation update, but I'll try to tackle it once I have some time. Once I get to it, I'll create a PR and mention you - I'd love your help with the docs (if you're still interested at the time).
